namespace NetScopeDiagnosticCenter.Core.Models.Wifi;

/// <summary>
/// Top-level verdict for the active Wi-Fi connection — drives Section 9 (Recommendations).
///
/// Score is 0..100, with weighted contributions:
///   <list type="bullet">
///     <item>Signal strength:    40 points (Excellent=40, Good=30, Fair=15, Poor=5)</item>
///     <item>Channel congestion: 30 points (Free=30, Light=22, Moderate=12, Heavy=4)</item>
///     <item>Security:           15 points (WPA3=15, WPA2=12, WPA=5, Open/WEP=0)</item>
///     <item>PHY generation:     15 points (Wi-Fi 6/6E/7=15, Wi-Fi 5=12, Wi-Fi 4=8, &lt;n=3)</item>
///   </list>
///
/// Verdict is one of: "Excellent" (≥85) / "Good" (≥70) / "Fair" (≥50) / "Poor" (&lt;50) /
/// "Not connected" / "No data".
///
/// Recommendations are actionable strings (max 5) generated by <c>WifiAnalyzerEngine</c>:
///   "📡 Channel 1 has 7 APs (heavy congestion). Consider switching to channel 11."
///   "🛡️ Network uses WPA2 — upgrade to WPA3 for forward secrecy."
///   "📶 Signal -82 dBm (poor). Move closer to AP or check obstructions."
///   etc.
/// </summary>
public sealed record WifiHealthReport(
    int? Score,
    string Verdict,
    int SignalContribution,
    int CongestionContribution,
    int SecurityContribution,
    int PhyContribution,
    IReadOnlyList<string> Recommendations,
    DateTimeOffset GeneratedAt)
{
    /// <summary>Sentinel for "no Wi-Fi connection — nothing to score".</summary>
    public static WifiHealthReport NotConnected() => new(
        Score: null,
        Verdict: "Not connected",
        SignalContribution: 0, CongestionContribution: 0, SecurityContribution: 0, PhyContribution: 0,
        Recommendations: new[] { "Connect to a Wi-Fi network to see analysis." },
        GeneratedAt: DateTimeOffset.Now);

    /// <summary>Sentinel for "scan hasn't run yet".</summary>
    public static WifiHealthReport NoData() => new(
        Score: null,
        Verdict: "No data",
        SignalContribution: 0, CongestionContribution: 0, SecurityContribution: 0, PhyContribution: 0,
        Recommendations: Array.Empty<string>(),
        GeneratedAt: DateTimeOffset.Now);
}
